---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: centos-6.4

suites:
  - name: default
    run_list:
      sandy-worker::sidekiq
    attributes:
      sandy-worker:
        user: vagrant
        worker-dir: /home/vagrant/sandy-project/jobs
